name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Build
      run: make build

    - uses: golangci/golangci-lint-action@v7
      with:
        version: v2.11.4

    - name: Unit Test
      run: make test

    - name: Integration Test
      run: make test-integration
