name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install asdf & tools
      uses: asdf-vm/actions/install@v3

    - name: Release
      run: goreleaser build --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
